# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - task fe:install
    - task fe:build

builds:
  - id: server
    main: ./cmd/gexec-server
    binary: gexec-server
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -extldflags "-static" -X "github.com/gexec/gexec/pkg/version.String={{.Version}}" -X "github.com/gexec/gexec/pkg/version.Revision={{.Commit}}" -X "github.com/gexec/gexec/pkg/version.Date={{.Date}}"
    tags:
      - netgo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
  - id: runner
    main: ./cmd/gexec-runner
    binary: gexec-runner
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -extldflags "-static" -X "github.com/gexec/gexec/pkg/version.String={{.Version}}" -X "github.com/gexec/gexec/pkg/version.Revision={{.Commit}}" -X "github.com/gexec/gexec/pkg/version.Date={{.Date}}"
    tags:
      - netgo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
  - id: client
    main: ./cmd/gexec-client
    binary: gexec-client
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -extldflags "-static" -X "github.com/gexec/gexec/pkg/version.String={{.Version}}" -X "github.com/gexec/gexec/pkg/version.Revision={{.Commit}}" -X "github.com/gexec/gexec/pkg/version.Date={{.Date}}"
    tags:
      - netgo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm

archives:
  - id: server
    ids:
      - server
    name_template: "gexec-server-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - CHANGELOG.md
      - src: cmd/gexec-server/README.md
        dst: README.md

  - id: runner
    ids:
      - runner
    name_template: "gexec-runner-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - CHANGELOG.md
      - src: cmd/gexec-runner/README.md
        dst: README.md

  - id: client
    ids:
      - client
    name_template: "gexec-client-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - CHANGELOG.md
      - src: cmd/gexec-client/README.md
        dst: README.md

nfpms:
  - id: server
    ids:
      - server
    package_name: gexec-server
    file_name_template: "gexec-server-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}"
    vendor: Gexec
    homepage: https://gexec.eu
    maintainer: Thomas Boerger <thomas@webhippie.de>
    description: |-
      Server for the generic execution platform for Ansible/OpenTodu/Terraform
    license: Apache 2.0
    formats:
      - deb
      - rpm
    dependencies:
      - git
    recommends:
      - ansible
    contents:
      - src: packaging/systemd/server.rpm.service
        dst: /usr/lib/systemd/system/gexec-server.service
        packager: rpm
      - src: packaging/systemd/server.deb.service
        dst: /usr/lib/systemd/system/gexec-server.service
        packager: deb
      - src: packaging/systemd/server.env
        dst: /etc/sysconfig/gexec-server
        packager: rpm
      - src: packaging/systemd/server.env
        dst: /etc/default/gexec-server
        packager: deb
      - src: packaging/systemd/server.yaml
        dst: /etc/gexec/server.yaml
        type: config|noreplace
      - src: packaging/systemd/auth.yaml
        dst: /etc/gexec/auth.yaml
        type: config|noreplace
      - dst: /var/lib/gexec
        type: dir
  - id: runner
    ids:
      - runner
    package_name: gexec-runner
    file_name_template: "gexec-runner-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}"
    vendor: Gexec
    homepage: https://gexec.eu
    maintainer: Thomas Boerger <thomas@webhippie.de>
    description: |-
      Runner for the generic execution platform for Ansible/OpenTodu/Terraform
    license: Apache 2.0
    formats:
      - deb
      - rpm
    dependencies:
      - git
    recommends:
      - ansible
    contents:
      - src: packaging/systemd/runner.rpm.service
        dst: /usr/lib/systemd/system/gexec-runner.service
        packager: rpm
      - src: packaging/systemd/runner.deb.service
        dst: /usr/lib/systemd/system/gexec-runner.service
        packager: deb
      - src: packaging/systemd/runner.env
        dst: /etc/sysconfig/gexec-runner
        packager: rpm
      - src: packaging/systemd/runner.env
        dst: /etc/default/gexec-runner
        packager: deb
      - src: packaging/systemd/runner.yaml
        dst: /etc/gexec/runner.yaml
        type: config|noreplace
      - dst: /var/lib/gexec
        type: dir
  - id: client
    ids:
      - client
    package_name: gexec-client
    file_name_template: "gexec-client-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}"
    vendor: Gexec
    homepage: https://gexec.eu
    maintainer: Thomas Boerger <thomas@webhippie.de>
    description: |-
      Client for the generic execution platform for Ansible/OpenTodu/Terraform
    license: Apache 2.0
    formats:
      - deb
      - rpm

signs:
  - id: archives
    signature: "${artifact}.asc"
    cmd: gpg2
    artifacts: archive
    args:
      - --batch
      - --armor
      - --local-user
      - 00753823B686D98A56DFD4BC15223049735CB53A
      - --output
      - ${signature}
      - --detach-sign
      - ${artifact}
  - id: packages
    signature: "${artifact}.asc"
    cmd: gpg2
    artifacts: package
    args:
      - --batch
      - --armor
      - --local-user
      - 00753823B686D98A56DFD4BC15223049735CB53A
      - --output
      - ${signature}
      - --detach-sign
      - ${artifact}

snapshot:
  version_template: testing

changelog:
  disable: true

checksum:
  disable: false
  split: true
