version: '3.4'

volumes:
  mariadb:

services:
  server:
    environment:
      - GEXEC_DATABASE_DRIVER=mysql
      - GEXEC_DATABASE_ADDRESS=db
      - GEXEC_DATABASE_PORT=3306
      - GEXEC_DATABASE_USERNAME=gexec
      - GEXEC_DATABASE_PASSWORD=gexec
      - GEXEC_DATABASE_NAME=gexec
    depends_on:
      - db

  db:
    image: mariadb:10.8
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=gexec
      - MARIADB_PASSWORD=gexec
      - MARIADB_DATABASE=gexec
    volumes:
      - mariadb:/var/lib/mysql
