version: '3.4'

volumes:
  postgres:

services:
  server:
    environment:
      - GEXEC_DATABASE_DRIVER=postgres
      - GEXEC_DATABASE_ADDRESS=db
      - GEXEC_DATABASE_PORT=5432
      - GEXEC_DATABASE_USERNAME=gexec
      - GEXEC_DATABASE_PASSWORD=gexec
      - GEXEC_DATABASE_NAME=gexec
    depends_on:
      - db

  db:
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_USER=gexec
      - POSTGRES_PASSWORD=gexec
      - POSTGRES_DB=gexec
    volumes:
      - postgres:/var/lib/postgresql
