{{- if not .Values.config.encrypt.existingSecret }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "gexec.fullname" . }}-encrypt
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gexec.labels" . | nindent 4 }}

type: Opaque
data:
  {{- $secretName := printf "%s-encrypt" (include "gexec.fullname" .) }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $passphraseValue := (get $secretData .Values.config.encrypt.passphraseKey) | default (randAlphaNum 32 | b64enc) }}
  {{ .Values.config.encrypt.passphraseKey }}: {{ if .Values.config.encrypt.passphrase }}{{ .Values.config.encrypt.passphrase | b64enc }}{{ else }}{{ $passphraseValue }}{{ end }}
{{- end }}
