{{- if not .Values.config.runner.existingSecret }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "gexec.fullname" . }}-runner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gexec.labels" . | nindent 4 }}

type: Opaque
data:
  {{- $secretName := printf "%s-runner" (include "gexec.fullname" .) }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $tokenValue := (get $secretData .Values.config.runner.tokenKey) | default (randAlphaNum 32 | b64enc) }}
  {{ .Values.config.runner.tokenKey }}: {{ if .Values.config.runner.token }}{{ .Values.config.runner.token | b64enc }}{{ else }}{{ $tokenValue }}{{ end }}
{{- end }}
