// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from './client'
import { client } from './client.gen'
import type {
  AttachGroupToProjectData,
  AttachGroupToProjectErrors,
  AttachGroupToProjectResponses,
  AttachGroupToUserData,
  AttachGroupToUserErrors,
  AttachGroupToUserResponses,
  AttachProjectToGroupData,
  AttachProjectToGroupErrors,
  AttachProjectToGroupResponses,
  AttachProjectToUserData,
  AttachProjectToUserErrors,
  AttachProjectToUserResponses,
  AttachUserToGroupData,
  AttachUserToGroupErrors,
  AttachUserToGroupResponses,
  AttachUserToProjectData,
  AttachUserToProjectErrors,
  AttachUserToProjectResponses,
  CallbackProviderData,
  CallbackProviderErrors,
  CreateGlobalRunnerData,
  CreateGlobalRunnerErrors,
  CreateGlobalRunnerResponses,
  CreateGroupData,
  CreateGroupErrors,
  CreateGroupResponses,
  CreateProjectCredentialData,
  CreateProjectCredentialErrors,
  CreateProjectCredentialResponses,
  CreateProjectData,
  CreateProjectEnvironmentData,
  CreateProjectEnvironmentErrors,
  CreateProjectEnvironmentResponses,
  CreateProjectEnvironmentSecretData,
  CreateProjectEnvironmentSecretErrors,
  CreateProjectEnvironmentSecretResponses,
  CreateProjectEnvironmentValueData,
  CreateProjectEnvironmentValueErrors,
  CreateProjectEnvironmentValueResponses,
  CreateProjectErrors,
  CreateProjectExecutionData,
  CreateProjectExecutionErrors,
  CreateProjectExecutionResponses,
  CreateProjectInventoryData,
  CreateProjectInventoryErrors,
  CreateProjectInventoryResponses,
  CreateProjectRepositoryData,
  CreateProjectRepositoryErrors,
  CreateProjectRepositoryResponses,
  CreateProjectResponses,
  CreateProjectRunnerData,
  CreateProjectRunnerErrors,
  CreateProjectRunnerResponses,
  CreateProjectScheduleData,
  CreateProjectScheduleErrors,
  CreateProjectScheduleResponses,
  CreateProjectTemplateData,
  CreateProjectTemplateErrors,
  CreateProjectTemplateResponses,
  CreateProjectTemplateSurveyData,
  CreateProjectTemplateSurveyErrors,
  CreateProjectTemplateSurveyResponses,
  CreateProjectTemplateVaultData,
  CreateProjectTemplateVaultErrors,
  CreateProjectTemplateVaultResponses,
  CreateUserData,
  CreateUserErrors,
  CreateUserResponses,
  DeleteGlobalRunnerData,
  DeleteGlobalRunnerErrors,
  DeleteGlobalRunnerResponses,
  DeleteGroupData,
  DeleteGroupErrors,
  DeleteGroupFromProjectData,
  DeleteGroupFromProjectErrors,
  DeleteGroupFromProjectResponses,
  DeleteGroupFromUserData,
  DeleteGroupFromUserErrors,
  DeleteGroupFromUserResponses,
  DeleteGroupResponses,
  DeleteProjectCredentialData,
  DeleteProjectCredentialErrors,
  DeleteProjectCredentialResponses,
  DeleteProjectData,
  DeleteProjectEnvironmentData,
  DeleteProjectEnvironmentErrors,
  DeleteProjectEnvironmentResponses,
  DeleteProjectEnvironmentSecretData,
  DeleteProjectEnvironmentSecretErrors,
  DeleteProjectEnvironmentSecretResponses,
  DeleteProjectEnvironmentValueData,
  DeleteProjectEnvironmentValueErrors,
  DeleteProjectEnvironmentValueResponses,
  DeleteProjectErrors,
  DeleteProjectExecutionData,
  DeleteProjectExecutionErrors,
  DeleteProjectExecutionResponses,
  DeleteProjectFromGroupData,
  DeleteProjectFromGroupErrors,
  DeleteProjectFromGroupResponses,
  DeleteProjectFromUserData,
  DeleteProjectFromUserErrors,
  DeleteProjectFromUserResponses,
  DeleteProjectInventoryData,
  DeleteProjectInventoryErrors,
  DeleteProjectInventoryResponses,
  DeleteProjectRepositoryData,
  DeleteProjectRepositoryErrors,
  DeleteProjectRepositoryResponses,
  DeleteProjectResponses,
  DeleteProjectRunnerData,
  DeleteProjectRunnerErrors,
  DeleteProjectRunnerResponses,
  DeleteProjectScheduleData,
  DeleteProjectScheduleErrors,
  DeleteProjectScheduleResponses,
  DeleteProjectTemplateData,
  DeleteProjectTemplateErrors,
  DeleteProjectTemplateResponses,
  DeleteProjectTemplateSurveyData,
  DeleteProjectTemplateSurveyErrors,
  DeleteProjectTemplateSurveyResponses,
  DeleteProjectTemplateVaultData,
  DeleteProjectTemplateVaultErrors,
  DeleteProjectTemplateVaultResponses,
  DeleteUserData,
  DeleteUserErrors,
  DeleteUserFromGroupData,
  DeleteUserFromGroupErrors,
  DeleteUserFromGroupResponses,
  DeleteUserFromProjectData,
  DeleteUserFromProjectErrors,
  DeleteUserFromProjectResponses,
  DeleteUserResponses,
  ListGlobalEventsData,
  ListGlobalEventsErrors,
  ListGlobalEventsResponses,
  ListGlobalRunnersData,
  ListGlobalRunnersErrors,
  ListGlobalRunnersResponses,
  ListGroupProjectsData,
  ListGroupProjectsErrors,
  ListGroupProjectsResponses,
  ListGroupsData,
  ListGroupsErrors,
  ListGroupsResponses,
  ListGroupUsersData,
  ListGroupUsersErrors,
  ListGroupUsersResponses,
  ListProjectCredentialsData,
  ListProjectCredentialsErrors,
  ListProjectCredentialsResponses,
  ListProjectEnvironmentsData,
  ListProjectEnvironmentsErrors,
  ListProjectEnvironmentsResponses,
  ListProjectEventsData,
  ListProjectEventsErrors,
  ListProjectEventsResponses,
  ListProjectExecutionsData,
  ListProjectExecutionsErrors,
  ListProjectExecutionsResponses,
  ListProjectGroupsData,
  ListProjectGroupsErrors,
  ListProjectGroupsResponses,
  ListProjectInventoriesData,
  ListProjectInventoriesErrors,
  ListProjectInventoriesResponses,
  ListProjectRepositoriesData,
  ListProjectRepositoriesErrors,
  ListProjectRepositoriesResponses,
  ListProjectRunnersData,
  ListProjectRunnersErrors,
  ListProjectRunnersResponses,
  ListProjectSchedulesData,
  ListProjectSchedulesErrors,
  ListProjectSchedulesResponses,
  ListProjectsData,
  ListProjectsErrors,
  ListProjectsResponses,
  ListProjectTemplatesData,
  ListProjectTemplatesErrors,
  ListProjectTemplatesResponses,
  ListProjectUsersData,
  ListProjectUsersErrors,
  ListProjectUsersResponses,
  ListProvidersData,
  ListProvidersResponses,
  ListUserGroupsData,
  ListUserGroupsErrors,
  ListUserGroupsResponses,
  ListUserProjectsData,
  ListUserProjectsErrors,
  ListUserProjectsResponses,
  ListUsersData,
  ListUsersErrors,
  ListUsersResponses,
  LoginAuthData,
  LoginAuthErrors,
  LoginAuthResponses,
  OutputProjectExecutionData,
  OutputProjectExecutionErrors,
  OutputProjectExecutionResponses,
  PermitGroupProjectData,
  PermitGroupProjectErrors,
  PermitGroupProjectResponses,
  PermitGroupUserData,
  PermitGroupUserErrors,
  PermitGroupUserResponses,
  PermitProjectGroupData,
  PermitProjectGroupErrors,
  PermitProjectGroupResponses,
  PermitProjectUserData,
  PermitProjectUserErrors,
  PermitProjectUserResponses,
  PermitUserGroupData,
  PermitUserGroupErrors,
  PermitUserGroupResponses,
  PermitUserProjectData,
  PermitUserProjectErrors,
  PermitUserProjectResponses,
  PurgeProjectExecutionData,
  PurgeProjectExecutionErrors,
  PurgeProjectExecutionResponses,
  RedirectAuthData,
  RedirectAuthErrors,
  RedirectAuthResponses,
  RefreshAuthData,
  RefreshAuthErrors,
  RefreshAuthResponses,
  RequestProviderData,
  RequestProviderErrors,
  ShowGlobalRunnerData,
  ShowGlobalRunnerErrors,
  ShowGlobalRunnerResponses,
  ShowGroupData,
  ShowGroupErrors,
  ShowGroupResponses,
  ShowProfileData,
  ShowProfileErrors,
  ShowProfileResponses,
  ShowProjectCredentialData,
  ShowProjectCredentialErrors,
  ShowProjectCredentialResponses,
  ShowProjectData,
  ShowProjectEnvironmentData,
  ShowProjectEnvironmentErrors,
  ShowProjectEnvironmentResponses,
  ShowProjectErrors,
  ShowProjectExecutionData,
  ShowProjectExecutionErrors,
  ShowProjectExecutionResponses,
  ShowProjectInventoryData,
  ShowProjectInventoryErrors,
  ShowProjectInventoryResponses,
  ShowProjectRepositoryData,
  ShowProjectRepositoryErrors,
  ShowProjectRepositoryResponses,
  ShowProjectResponses,
  ShowProjectRunnerData,
  ShowProjectRunnerErrors,
  ShowProjectRunnerResponses,
  ShowProjectScheduleData,
  ShowProjectScheduleErrors,
  ShowProjectScheduleResponses,
  ShowProjectTemplateData,
  ShowProjectTemplateErrors,
  ShowProjectTemplateResponses,
  ShowUserData,
  ShowUserErrors,
  ShowUserResponses,
  TokenProfileData,
  TokenProfileErrors,
  TokenProfileResponses,
  UpdateGlobalRunnerData,
  UpdateGlobalRunnerErrors,
  UpdateGlobalRunnerResponses,
  UpdateGroupData,
  UpdateGroupErrors,
  UpdateGroupResponses,
  UpdateProfileData,
  UpdateProfileErrors,
  UpdateProfileResponses,
  UpdateProjectCredentialData,
  UpdateProjectCredentialErrors,
  UpdateProjectCredentialResponses,
  UpdateProjectData,
  UpdateProjectEnvironmentData,
  UpdateProjectEnvironmentErrors,
  UpdateProjectEnvironmentResponses,
  UpdateProjectEnvironmentSecretData,
  UpdateProjectEnvironmentSecretErrors,
  UpdateProjectEnvironmentSecretResponses,
  UpdateProjectEnvironmentValueData,
  UpdateProjectEnvironmentValueErrors,
  UpdateProjectEnvironmentValueResponses,
  UpdateProjectErrors,
  UpdateProjectInventoryData,
  UpdateProjectInventoryErrors,
  UpdateProjectInventoryResponses,
  UpdateProjectRepositoryData,
  UpdateProjectRepositoryErrors,
  UpdateProjectRepositoryResponses,
  UpdateProjectResponses,
  UpdateProjectRunnerData,
  UpdateProjectRunnerErrors,
  UpdateProjectRunnerResponses,
  UpdateProjectScheduleData,
  UpdateProjectScheduleErrors,
  UpdateProjectScheduleResponses,
  UpdateProjectTemplateData,
  UpdateProjectTemplateErrors,
  UpdateProjectTemplateResponses,
  UpdateProjectTemplateSurveyData,
  UpdateProjectTemplateSurveyErrors,
  UpdateProjectTemplateSurveyResponses,
  UpdateProjectTemplateVaultData,
  UpdateProjectTemplateVaultErrors,
  UpdateProjectTemplateVaultResponses,
  UpdateUserData,
  UpdateUserErrors,
  UpdateUserResponses,
  VerifyAuthData,
  VerifyAuthErrors,
  VerifyAuthResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Request the redirect to defined provider
 */
export const requestProvider = <ThrowOnError extends boolean = false>(
  options: Options<RequestProviderData, ThrowOnError>
): RequestResult<unknown, RequestProviderErrors, ThrowOnError> =>
  (options.client ?? client).get<unknown, RequestProviderErrors, ThrowOnError>({
    url: '/auth/{provider}/request',
    ...options,
  })

/**
 * Callback to parse the defined provider
 */
export const callbackProvider = <ThrowOnError extends boolean = false>(
  options: Options<CallbackProviderData, ThrowOnError>
): RequestResult<unknown, CallbackProviderErrors, ThrowOnError> =>
  (options.client ?? client).get<unknown, CallbackProviderErrors, ThrowOnError>(
    { url: '/auth/{provider}/callback', ...options }
  )

/**
 * Fetch the available auth providers
 */
export const listProviders = <ThrowOnError extends boolean = false>(
  options?: Options<ListProvidersData, ThrowOnError>
): RequestResult<ListProvidersResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ListProvidersResponses,
    unknown,
    ThrowOnError
  >({ url: '/auth/providers', ...options })

/**
 * Retrieve real token after redirect
 */
export const redirectAuth = <ThrowOnError extends boolean = false>(
  options: Options<RedirectAuthData, ThrowOnError>
): RequestResult<RedirectAuthResponses, RedirectAuthErrors, ThrowOnError> =>
  (options.client ?? client).post<
    RedirectAuthResponses,
    RedirectAuthErrors,
    ThrowOnError
  >({
    url: '/auth/redirect',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Authenticate an user by credentials
 */
export const loginAuth = <ThrowOnError extends boolean = false>(
  options: Options<LoginAuthData, ThrowOnError>
): RequestResult<LoginAuthResponses, LoginAuthErrors, ThrowOnError> =>
  (options.client ?? client).post<
    LoginAuthResponses,
    LoginAuthErrors,
    ThrowOnError
  >({
    url: '/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Refresh an auth token before it expires
 */
export const refreshAuth = <ThrowOnError extends boolean = false>(
  options?: Options<RefreshAuthData, ThrowOnError>
): RequestResult<RefreshAuthResponses, RefreshAuthErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    RefreshAuthResponses,
    RefreshAuthErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/auth/refresh',
    ...options,
  })

/**
 * Verify validity for an authentication token
 */
export const verifyAuth = <ThrowOnError extends boolean = false>(
  options?: Options<VerifyAuthData, ThrowOnError>
): RequestResult<VerifyAuthResponses, VerifyAuthErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    VerifyAuthResponses,
    VerifyAuthErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/auth/verify',
    ...options,
  })

/**
 * Retrieve an unlimited auth token
 */
export const tokenProfile = <ThrowOnError extends boolean = false>(
  options?: Options<TokenProfileData, ThrowOnError>
): RequestResult<TokenProfileResponses, TokenProfileErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    TokenProfileResponses,
    TokenProfileErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/profile/token',
    ...options,
  })

/**
 * Fetch profile details of the personal account
 */
export const showProfile = <ThrowOnError extends boolean = false>(
  options?: Options<ShowProfileData, ThrowOnError>
): RequestResult<ShowProfileResponses, ShowProfileErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ShowProfileResponses,
    ShowProfileErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/profile/self',
    ...options,
  })

/**
 * Update your own profile information
 */
export const updateProfile = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProfileData, ThrowOnError>
): RequestResult<UpdateProfileResponses, UpdateProfileErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateProfileResponses,
    UpdateProfileErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/profile/self',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Fetch all available projects
 */
export const listProjects = <ThrowOnError extends boolean = false>(
  options?: Options<ListProjectsData, ThrowOnError>
): RequestResult<ListProjectsResponses, ListProjectsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListProjectsResponses,
    ListProjectsErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects',
    ...options,
  })

/**
 * Create a new project
 */
export const createProject = <ThrowOnError extends boolean = false>(
  options: Options<CreateProjectData, ThrowOnError>
): RequestResult<CreateProjectResponses, CreateProjectErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateProjectResponses,
    CreateProjectErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete a specific project
 */
export const deleteProject = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProjectData, ThrowOnError>
): RequestResult<DeleteProjectResponses, DeleteProjectErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteProjectResponses,
    DeleteProjectErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}',
    ...options,
  })

/**
 * Fetch a specific project
 */
export const showProject = <ThrowOnError extends boolean = false>(
  options: Options<ShowProjectData, ThrowOnError>
): RequestResult<ShowProjectResponses, ShowProjectErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ShowProjectResponses,
    ShowProjectErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}',
    ...options,
  })

/**
 * Update a specific project
 */
export const updateProject = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProjectData, ThrowOnError>
): RequestResult<UpdateProjectResponses, UpdateProjectErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateProjectResponses,
    UpdateProjectErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Unlink a user from project
 */
export const deleteProjectFromUser = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProjectFromUserData, ThrowOnError>
): RequestResult<
  DeleteProjectFromUserResponses,
  DeleteProjectFromUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteProjectFromUserResponses,
    DeleteProjectFromUserErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Fetch all users attached to project
 */
export const listProjectUsers = <ThrowOnError extends boolean = false>(
  options: Options<ListProjectUsersData, ThrowOnError>
): RequestResult<
  ListProjectUsersResponses,
  ListProjectUsersErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListProjectUsersResponses,
    ListProjectUsersErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/users',
    ...options,
  })

/**
 * Attach a user to project
 */
export const attachProjectToUser = <ThrowOnError extends boolean = false>(
  options: Options<AttachProjectToUserData, ThrowOnError>
): RequestResult<
  AttachProjectToUserResponses,
  AttachProjectToUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AttachProjectToUserResponses,
    AttachProjectToUserErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Update user perms for project
 */
export const permitProjectUser = <ThrowOnError extends boolean = false>(
  options: Options<PermitProjectUserData, ThrowOnError>
): RequestResult<
  PermitProjectUserResponses,
  PermitProjectUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PermitProjectUserResponses,
    PermitProjectUserErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Unlink a group from project
 */
export const deleteProjectFromGroup = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProjectFromGroupData, ThrowOnError>
): RequestResult<
  DeleteProjectFromGroupResponses,
  DeleteProjectFromGroupErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteProjectFromGroupResponses,
    DeleteProjectFromGroupErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/groups',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Fetch all groups attached to project
 */
export const listProjectGroups = <ThrowOnError extends boolean = false>(
  options: Options<ListProjectGroupsData, ThrowOnError>
): RequestResult<
  ListProjectGroupsResponses,
  ListProjectGroupsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListProjectGroupsResponses,
    ListProjectGroupsErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/groups',
    ...options,
  })

/**
 * Attach a group to project
 */
export const attachProjectToGroup = <ThrowOnError extends boolean = false>(
  options: Options<AttachProjectToGroupData, ThrowOnError>
): RequestResult<
  AttachProjectToGroupResponses,
  AttachProjectToGroupErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AttachProjectToGroupResponses,
    AttachProjectToGroupErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/groups',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Update group perms for project
 */
export const permitProjectGroup = <ThrowOnError extends boolean = false>(
  options: Options<PermitProjectGroupData, ThrowOnError>
): RequestResult<
  PermitProjectGroupResponses,
  PermitProjectGroupErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PermitProjectGroupResponses,
    PermitProjectGroupErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/groups',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Fetch all events for a project
 */
export const listProjectEvents = <ThrowOnError extends boolean = false>(
  options: Options<ListProjectEventsData, ThrowOnError>
): RequestResult<
  ListProjectEventsResponses,
  ListProjectEventsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListProjectEventsResponses,
    ListProjectEventsErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/events',
    ...options,
  })

/**
 * Fetch all runners for a project
 */
export const listProjectRunners = <ThrowOnError extends boolean = false>(
  options: Options<ListProjectRunnersData, ThrowOnError>
): RequestResult<
  ListProjectRunnersResponses,
  ListProjectRunnersErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListProjectRunnersResponses,
    ListProjectRunnersErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/runners',
    ...options,
  })

/**
 * Create a new runner
 */
export const createProjectRunner = <ThrowOnError extends boolean = false>(
  options: Options<CreateProjectRunnerData, ThrowOnError>
): RequestResult<
  CreateProjectRunnerResponses,
  CreateProjectRunnerErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateProjectRunnerResponses,
    CreateProjectRunnerErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/runners',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete a specific runner for a project
 */
export const deleteProjectRunner = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProjectRunnerData, ThrowOnError>
): RequestResult<
  DeleteProjectRunnerResponses,
  DeleteProjectRunnerErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteProjectRunnerResponses,
    DeleteProjectRunnerErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/runners/{runner_id}',
    ...options,
  })

/**
 * Fetch a specific runner for a project
 */
export const showProjectRunner = <ThrowOnError extends boolean = false>(
  options: Options<ShowProjectRunnerData, ThrowOnError>
): RequestResult<
  ShowProjectRunnerResponses,
  ShowProjectRunnerErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ShowProjectRunnerResponses,
    ShowProjectRunnerErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/runners/{runner_id}',
    ...options,
  })

/**
 * Update a specific runner for a project
 */
export const updateProjectRunner = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProjectRunnerData, ThrowOnError>
): RequestResult<
  UpdateProjectRunnerResponses,
  UpdateProjectRunnerErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateProjectRunnerResponses,
    UpdateProjectRunnerErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/runners/{runner_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Fetch all credentials for a project
 */
export const listProjectCredentials = <ThrowOnError extends boolean = false>(
  options: Options<ListProjectCredentialsData, ThrowOnError>
): RequestResult<
  ListProjectCredentialsResponses,
  ListProjectCredentialsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListProjectCredentialsResponses,
    ListProjectCredentialsErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/credentials',
    ...options,
  })

/**
 * Create a new credential
 */
export const createProjectCredential = <ThrowOnError extends boolean = false>(
  options: Options<CreateProjectCredentialData, ThrowOnError>
): RequestResult<
  CreateProjectCredentialResponses,
  CreateProjectCredentialErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateProjectCredentialResponses,
    CreateProjectCredentialErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/credentials',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete a specific credential for a project
 */
export const deleteProjectCredential = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProjectCredentialData, ThrowOnError>
): RequestResult<
  DeleteProjectCredentialResponses,
  DeleteProjectCredentialErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteProjectCredentialResponses,
    DeleteProjectCredentialErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/credentials/{credential_id}',
    ...options,
  })

/**
 * Fetch a specific credential for a project
 */
export const showProjectCredential = <ThrowOnError extends boolean = false>(
  options: Options<ShowProjectCredentialData, ThrowOnError>
): RequestResult<
  ShowProjectCredentialResponses,
  ShowProjectCredentialErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ShowProjectCredentialResponses,
    ShowProjectCredentialErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/credentials/{credential_id}',
    ...options,
  })

/**
 * Update a specific credential for a project
 */
export const updateProjectCredential = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProjectCredentialData, ThrowOnError>
): RequestResult<
  UpdateProjectCredentialResponses,
  UpdateProjectCredentialErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateProjectCredentialResponses,
    UpdateProjectCredentialErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/credentials/{credential_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Fetch all repositories for a project
 */
export const listProjectRepositories = <ThrowOnError extends boolean = false>(
  options: Options<ListProjectRepositoriesData, ThrowOnError>
): RequestResult<
  ListProjectRepositoriesResponses,
  ListProjectRepositoriesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListProjectRepositoriesResponses,
    ListProjectRepositoriesErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/repositories',
    ...options,
  })

/**
 * Create a new repository
 */
export const createProjectRepository = <ThrowOnError extends boolean = false>(
  options: Options<CreateProjectRepositoryData, ThrowOnError>
): RequestResult<
  CreateProjectRepositoryResponses,
  CreateProjectRepositoryErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateProjectRepositoryResponses,
    CreateProjectRepositoryErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/repositories',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete a specific repository for a project
 */
export const deleteProjectRepository = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProjectRepositoryData, ThrowOnError>
): RequestResult<
  DeleteProjectRepositoryResponses,
  DeleteProjectRepositoryErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteProjectRepositoryResponses,
    DeleteProjectRepositoryErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/repositories/{repository_id}',
    ...options,
  })

/**
 * Fetch a specific repository for a project
 */
export const showProjectRepository = <ThrowOnError extends boolean = false>(
  options: Options<ShowProjectRepositoryData, ThrowOnError>
): RequestResult<
  ShowProjectRepositoryResponses,
  ShowProjectRepositoryErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ShowProjectRepositoryResponses,
    ShowProjectRepositoryErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/repositories/{repository_id}',
    ...options,
  })

/**
 * Update a specific repository for a project
 */
export const updateProjectRepository = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProjectRepositoryData, ThrowOnError>
): RequestResult<
  UpdateProjectRepositoryResponses,
  UpdateProjectRepositoryErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateProjectRepositoryResponses,
    UpdateProjectRepositoryErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/repositories/{repository_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Fetch all inventories for a project
 */
export const listProjectInventories = <ThrowOnError extends boolean = false>(
  options: Options<ListProjectInventoriesData, ThrowOnError>
): RequestResult<
  ListProjectInventoriesResponses,
  ListProjectInventoriesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListProjectInventoriesResponses,
    ListProjectInventoriesErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/inventories',
    ...options,
  })

/**
 * Create a new inventory
 */
export const createProjectInventory = <ThrowOnError extends boolean = false>(
  options: Options<CreateProjectInventoryData, ThrowOnError>
): RequestResult<
  CreateProjectInventoryResponses,
  CreateProjectInventoryErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateProjectInventoryResponses,
    CreateProjectInventoryErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/inventories',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete a specific inventory for a project
 */
export const deleteProjectInventory = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProjectInventoryData, ThrowOnError>
): RequestResult<
  DeleteProjectInventoryResponses,
  DeleteProjectInventoryErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteProjectInventoryResponses,
    DeleteProjectInventoryErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/inventories/{inventory_id}',
    ...options,
  })

/**
 * Fetch a specific inventory for a project
 */
export const showProjectInventory = <ThrowOnError extends boolean = false>(
  options: Options<ShowProjectInventoryData, ThrowOnError>
): RequestResult<
  ShowProjectInventoryResponses,
  ShowProjectInventoryErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ShowProjectInventoryResponses,
    ShowProjectInventoryErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/inventories/{inventory_id}',
    ...options,
  })

/**
 * Update a specific inventory for a project
 */
export const updateProjectInventory = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProjectInventoryData, ThrowOnError>
): RequestResult<
  UpdateProjectInventoryResponses,
  UpdateProjectInventoryErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateProjectInventoryResponses,
    UpdateProjectInventoryErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/inventories/{inventory_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Fetch all environments for a project
 */
export const listProjectEnvironments = <ThrowOnError extends boolean = false>(
  options: Options<ListProjectEnvironmentsData, ThrowOnError>
): RequestResult<
  ListProjectEnvironmentsResponses,
  ListProjectEnvironmentsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListProjectEnvironmentsResponses,
    ListProjectEnvironmentsErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/environments',
    ...options,
  })

/**
 * Create a new environment
 */
export const createProjectEnvironment = <ThrowOnError extends boolean = false>(
  options: Options<CreateProjectEnvironmentData, ThrowOnError>
): RequestResult<
  CreateProjectEnvironmentResponses,
  CreateProjectEnvironmentErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateProjectEnvironmentResponses,
    CreateProjectEnvironmentErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/environments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete a specific environment for a project
 */
export const deleteProjectEnvironment = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProjectEnvironmentData, ThrowOnError>
): RequestResult<
  DeleteProjectEnvironmentResponses,
  DeleteProjectEnvironmentErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteProjectEnvironmentResponses,
    DeleteProjectEnvironmentErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/environments/{environment_id}',
    ...options,
  })

/**
 * Fetch a specific environment for a project
 */
export const showProjectEnvironment = <ThrowOnError extends boolean = false>(
  options: Options<ShowProjectEnvironmentData, ThrowOnError>
): RequestResult<
  ShowProjectEnvironmentResponses,
  ShowProjectEnvironmentErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ShowProjectEnvironmentResponses,
    ShowProjectEnvironmentErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/environments/{environment_id}',
    ...options,
  })

/**
 * Update a specific environment for a project
 */
export const updateProjectEnvironment = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProjectEnvironmentData, ThrowOnError>
): RequestResult<
  UpdateProjectEnvironmentResponses,
  UpdateProjectEnvironmentErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateProjectEnvironmentResponses,
    UpdateProjectEnvironmentErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/environments/{environment_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Create a new secret on an environment
 */
export const createProjectEnvironmentSecret = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateProjectEnvironmentSecretData, ThrowOnError>
): RequestResult<
  CreateProjectEnvironmentSecretResponses,
  CreateProjectEnvironmentSecretErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateProjectEnvironmentSecretResponses,
    CreateProjectEnvironmentSecretErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/environments/{environment_id}/secrets',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete a secret on an environment for a project
 */
export const deleteProjectEnvironmentSecret = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteProjectEnvironmentSecretData, ThrowOnError>
): RequestResult<
  DeleteProjectEnvironmentSecretResponses,
  DeleteProjectEnvironmentSecretErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteProjectEnvironmentSecretResponses,
    DeleteProjectEnvironmentSecretErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/environments/{environment_id}/secrets/{secret_id}',
    ...options,
  })

/**
 * Update a secret on an environment for a project
 */
export const updateProjectEnvironmentSecret = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateProjectEnvironmentSecretData, ThrowOnError>
): RequestResult<
  UpdateProjectEnvironmentSecretResponses,
  UpdateProjectEnvironmentSecretErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateProjectEnvironmentSecretResponses,
    UpdateProjectEnvironmentSecretErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/environments/{environment_id}/secrets/{secret_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Create a new value on an environment
 */
export const createProjectEnvironmentValue = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateProjectEnvironmentValueData, ThrowOnError>
): RequestResult<
  CreateProjectEnvironmentValueResponses,
  CreateProjectEnvironmentValueErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateProjectEnvironmentValueResponses,
    CreateProjectEnvironmentValueErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/environments/{environment_id}/values',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete a value on an environment for a project
 */
export const deleteProjectEnvironmentValue = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteProjectEnvironmentValueData, ThrowOnError>
): RequestResult<
  DeleteProjectEnvironmentValueResponses,
  DeleteProjectEnvironmentValueErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteProjectEnvironmentValueResponses,
    DeleteProjectEnvironmentValueErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/environments/{environment_id}/values/{value_id}',
    ...options,
  })

/**
 * Update a value on an environment for a project
 */
export const updateProjectEnvironmentValue = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateProjectEnvironmentValueData, ThrowOnError>
): RequestResult<
  UpdateProjectEnvironmentValueResponses,
  UpdateProjectEnvironmentValueErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateProjectEnvironmentValueResponses,
    UpdateProjectEnvironmentValueErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/environments/{environment_id}/values/{value_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Fetch all templates for a project
 */
export const listProjectTemplates = <ThrowOnError extends boolean = false>(
  options: Options<ListProjectTemplatesData, ThrowOnError>
): RequestResult<
  ListProjectTemplatesResponses,
  ListProjectTemplatesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListProjectTemplatesResponses,
    ListProjectTemplatesErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/templates',
    ...options,
  })

/**
 * Create a new template
 */
export const createProjectTemplate = <ThrowOnError extends boolean = false>(
  options: Options<CreateProjectTemplateData, ThrowOnError>
): RequestResult<
  CreateProjectTemplateResponses,
  CreateProjectTemplateErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateProjectTemplateResponses,
    CreateProjectTemplateErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/templates',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete a specific template for a project
 */
export const deleteProjectTemplate = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProjectTemplateData, ThrowOnError>
): RequestResult<
  DeleteProjectTemplateResponses,
  DeleteProjectTemplateErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteProjectTemplateResponses,
    DeleteProjectTemplateErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/templates/{template_id}',
    ...options,
  })

/**
 * Fetch a specific template for a project
 */
export const showProjectTemplate = <ThrowOnError extends boolean = false>(
  options: Options<ShowProjectTemplateData, ThrowOnError>
): RequestResult<
  ShowProjectTemplateResponses,
  ShowProjectTemplateErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ShowProjectTemplateResponses,
    ShowProjectTemplateErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/templates/{template_id}',
    ...options,
  })

/**
 * Update a specific template for a project
 */
export const updateProjectTemplate = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProjectTemplateData, ThrowOnError>
): RequestResult<
  UpdateProjectTemplateResponses,
  UpdateProjectTemplateErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateProjectTemplateResponses,
    UpdateProjectTemplateErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/templates/{template_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Create a new survey on a template
 */
export const createProjectTemplateSurvey = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateProjectTemplateSurveyData, ThrowOnError>
): RequestResult<
  CreateProjectTemplateSurveyResponses,
  CreateProjectTemplateSurveyErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateProjectTemplateSurveyResponses,
    CreateProjectTemplateSurveyErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/templates/{template_id}/surveys',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete a survey on a template for a project
 */
export const deleteProjectTemplateSurvey = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteProjectTemplateSurveyData, ThrowOnError>
): RequestResult<
  DeleteProjectTemplateSurveyResponses,
  DeleteProjectTemplateSurveyErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteProjectTemplateSurveyResponses,
    DeleteProjectTemplateSurveyErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/templates/{template_id}/surveys/{survey_id}',
    ...options,
  })

/**
 * Update a survey on a template for a project
 */
export const updateProjectTemplateSurvey = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateProjectTemplateSurveyData, ThrowOnError>
): RequestResult<
  UpdateProjectTemplateSurveyResponses,
  UpdateProjectTemplateSurveyErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateProjectTemplateSurveyResponses,
    UpdateProjectTemplateSurveyErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/templates/{template_id}/surveys/{survey_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Create a new vault on a template
 */
export const createProjectTemplateVault = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateProjectTemplateVaultData, ThrowOnError>
): RequestResult<
  CreateProjectTemplateVaultResponses,
  CreateProjectTemplateVaultErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateProjectTemplateVaultResponses,
    CreateProjectTemplateVaultErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/templates/{template_id}/vaults',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete a vault on a template for a project
 */
export const deleteProjectTemplateVault = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteProjectTemplateVaultData, ThrowOnError>
): RequestResult<
  DeleteProjectTemplateVaultResponses,
  DeleteProjectTemplateVaultErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteProjectTemplateVaultResponses,
    DeleteProjectTemplateVaultErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/templates/{template_id}/vaults/{vault_id}',
    ...options,
  })

/**
 * Update a vault on a template for a project
 */
export const updateProjectTemplateVault = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateProjectTemplateVaultData, ThrowOnError>
): RequestResult<
  UpdateProjectTemplateVaultResponses,
  UpdateProjectTemplateVaultErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateProjectTemplateVaultResponses,
    UpdateProjectTemplateVaultErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/templates/{template_id}/vaults/{vault_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Fetch all schedules for a project
 */
export const listProjectSchedules = <ThrowOnError extends boolean = false>(
  options: Options<ListProjectSchedulesData, ThrowOnError>
): RequestResult<
  ListProjectSchedulesResponses,
  ListProjectSchedulesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListProjectSchedulesResponses,
    ListProjectSchedulesErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/schedules',
    ...options,
  })

/**
 * Create a new schedule
 */
export const createProjectSchedule = <ThrowOnError extends boolean = false>(
  options: Options<CreateProjectScheduleData, ThrowOnError>
): RequestResult<
  CreateProjectScheduleResponses,
  CreateProjectScheduleErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateProjectScheduleResponses,
    CreateProjectScheduleErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/schedules',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete a specific schedule for a project
 */
export const deleteProjectSchedule = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProjectScheduleData, ThrowOnError>
): RequestResult<
  DeleteProjectScheduleResponses,
  DeleteProjectScheduleErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteProjectScheduleResponses,
    DeleteProjectScheduleErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/schedules/{schedule_id}',
    ...options,
  })

/**
 * Fetch a specific schedule for a project
 */
export const showProjectSchedule = <ThrowOnError extends boolean = false>(
  options: Options<ShowProjectScheduleData, ThrowOnError>
): RequestResult<
  ShowProjectScheduleResponses,
  ShowProjectScheduleErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ShowProjectScheduleResponses,
    ShowProjectScheduleErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/schedules/{schedule_id}',
    ...options,
  })

/**
 * Update a specific schedule for a project
 */
export const updateProjectSchedule = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProjectScheduleData, ThrowOnError>
): RequestResult<
  UpdateProjectScheduleResponses,
  UpdateProjectScheduleErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateProjectScheduleResponses,
    UpdateProjectScheduleErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/schedules/{schedule_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Fetch all executions for a project
 */
export const listProjectExecutions = <ThrowOnError extends boolean = false>(
  options: Options<ListProjectExecutionsData, ThrowOnError>
): RequestResult<
  ListProjectExecutionsResponses,
  ListProjectExecutionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListProjectExecutionsResponses,
    ListProjectExecutionsErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/executions',
    ...options,
  })

/**
 * Create a new execution
 */
export const createProjectExecution = <ThrowOnError extends boolean = false>(
  options: Options<CreateProjectExecutionData, ThrowOnError>
): RequestResult<
  CreateProjectExecutionResponses,
  CreateProjectExecutionErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateProjectExecutionResponses,
    CreateProjectExecutionErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/executions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete a specific execution for a project
 */
export const deleteProjectExecution = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProjectExecutionData, ThrowOnError>
): RequestResult<
  DeleteProjectExecutionResponses,
  DeleteProjectExecutionErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteProjectExecutionResponses,
    DeleteProjectExecutionErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/executions/{execution_id}',
    ...options,
  })

/**
 * Fetch a specific execution for a project
 */
export const showProjectExecution = <ThrowOnError extends boolean = false>(
  options: Options<ShowProjectExecutionData, ThrowOnError>
): RequestResult<
  ShowProjectExecutionResponses,
  ShowProjectExecutionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ShowProjectExecutionResponses,
    ShowProjectExecutionErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/executions/{execution_id}',
    ...options,
  })

/**
 * Purge a specific execution for a project
 */
export const purgeProjectExecution = <ThrowOnError extends boolean = false>(
  options: Options<PurgeProjectExecutionData, ThrowOnError>
): RequestResult<
  PurgeProjectExecutionResponses,
  PurgeProjectExecutionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    PurgeProjectExecutionResponses,
    PurgeProjectExecutionErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/executions/{execution_id}/purge',
    ...options,
  })

/**
 * Output a specific execution for a project
 */
export const outputProjectExecution = <ThrowOnError extends boolean = false>(
  options: Options<OutputProjectExecutionData, ThrowOnError>
): RequestResult<
  OutputProjectExecutionResponses,
  OutputProjectExecutionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    OutputProjectExecutionResponses,
    OutputProjectExecutionErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/projects/{project_id}/executions/{execution_id}/output',
    ...options,
  })

/**
 * Fetch all events
 */
export const listGlobalEvents = <ThrowOnError extends boolean = false>(
  options?: Options<ListGlobalEventsData, ThrowOnError>
): RequestResult<
  ListGlobalEventsResponses,
  ListGlobalEventsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListGlobalEventsResponses,
    ListGlobalEventsErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/events',
    ...options,
  })

/**
 * Fetch all runners
 */
export const listGlobalRunners = <ThrowOnError extends boolean = false>(
  options?: Options<ListGlobalRunnersData, ThrowOnError>
): RequestResult<
  ListGlobalRunnersResponses,
  ListGlobalRunnersErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListGlobalRunnersResponses,
    ListGlobalRunnersErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/runners',
    ...options,
  })

/**
 * Create a new global runner
 */
export const createGlobalRunner = <ThrowOnError extends boolean = false>(
  options: Options<CreateGlobalRunnerData, ThrowOnError>
): RequestResult<
  CreateGlobalRunnerResponses,
  CreateGlobalRunnerErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateGlobalRunnerResponses,
    CreateGlobalRunnerErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/runners',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete a specific runner
 */
export const deleteGlobalRunner = <ThrowOnError extends boolean = false>(
  options: Options<DeleteGlobalRunnerData, ThrowOnError>
): RequestResult<
  DeleteGlobalRunnerResponses,
  DeleteGlobalRunnerErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteGlobalRunnerResponses,
    DeleteGlobalRunnerErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/runners/{runner_id}',
    ...options,
  })

/**
 * Fetch a specific runner
 */
export const showGlobalRunner = <ThrowOnError extends boolean = false>(
  options: Options<ShowGlobalRunnerData, ThrowOnError>
): RequestResult<
  ShowGlobalRunnerResponses,
  ShowGlobalRunnerErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ShowGlobalRunnerResponses,
    ShowGlobalRunnerErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/runners/{runner_id}',
    ...options,
  })

/**
 * Update a specific runner
 */
export const updateGlobalRunner = <ThrowOnError extends boolean = false>(
  options: Options<UpdateGlobalRunnerData, ThrowOnError>
): RequestResult<
  UpdateGlobalRunnerResponses,
  UpdateGlobalRunnerErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateGlobalRunnerResponses,
    UpdateGlobalRunnerErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/runners/{runner_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Fetch all available groups
 */
export const listGroups = <ThrowOnError extends boolean = false>(
  options?: Options<ListGroupsData, ThrowOnError>
): RequestResult<ListGroupsResponses, ListGroupsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListGroupsResponses,
    ListGroupsErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/groups',
    ...options,
  })

/**
 * Create a new group
 */
export const createGroup = <ThrowOnError extends boolean = false>(
  options: Options<CreateGroupData, ThrowOnError>
): RequestResult<CreateGroupResponses, CreateGroupErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateGroupResponses,
    CreateGroupErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/groups',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete a specific group
 */
export const deleteGroup = <ThrowOnError extends boolean = false>(
  options: Options<DeleteGroupData, ThrowOnError>
): RequestResult<DeleteGroupResponses, DeleteGroupErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteGroupResponses,
    DeleteGroupErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/groups/{group_id}',
    ...options,
  })

/**
 * Fetch a specific group
 */
export const showGroup = <ThrowOnError extends boolean = false>(
  options: Options<ShowGroupData, ThrowOnError>
): RequestResult<ShowGroupResponses, ShowGroupErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ShowGroupResponses,
    ShowGroupErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/groups/{group_id}',
    ...options,
  })

/**
 * Update a specific group
 */
export const updateGroup = <ThrowOnError extends boolean = false>(
  options: Options<UpdateGroupData, ThrowOnError>
): RequestResult<UpdateGroupResponses, UpdateGroupErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateGroupResponses,
    UpdateGroupErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/groups/{group_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Unlink a user from group
 */
export const deleteGroupFromUser = <ThrowOnError extends boolean = false>(
  options: Options<DeleteGroupFromUserData, ThrowOnError>
): RequestResult<
  DeleteGroupFromUserResponses,
  DeleteGroupFromUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteGroupFromUserResponses,
    DeleteGroupFromUserErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/groups/{group_id}/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Fetch all users attached to group
 */
export const listGroupUsers = <ThrowOnError extends boolean = false>(
  options: Options<ListGroupUsersData, ThrowOnError>
): RequestResult<ListGroupUsersResponses, ListGroupUsersErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ListGroupUsersResponses,
    ListGroupUsersErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/groups/{group_id}/users',
    ...options,
  })

/**
 * Attach a user to group
 */
export const attachGroupToUser = <ThrowOnError extends boolean = false>(
  options: Options<AttachGroupToUserData, ThrowOnError>
): RequestResult<
  AttachGroupToUserResponses,
  AttachGroupToUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AttachGroupToUserResponses,
    AttachGroupToUserErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/groups/{group_id}/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Update user perms for group
 */
export const permitGroupUser = <ThrowOnError extends boolean = false>(
  options: Options<PermitGroupUserData, ThrowOnError>
): RequestResult<
  PermitGroupUserResponses,
  PermitGroupUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PermitGroupUserResponses,
    PermitGroupUserErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/groups/{group_id}/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Unlink a project from group
 */
export const deleteGroupFromProject = <ThrowOnError extends boolean = false>(
  options: Options<DeleteGroupFromProjectData, ThrowOnError>
): RequestResult<
  DeleteGroupFromProjectResponses,
  DeleteGroupFromProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteGroupFromProjectResponses,
    DeleteGroupFromProjectErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/groups/{group_id}/projects',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Fetch all projects attached to group
 */
export const listGroupProjects = <ThrowOnError extends boolean = false>(
  options: Options<ListGroupProjectsData, ThrowOnError>
): RequestResult<
  ListGroupProjectsResponses,
  ListGroupProjectsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListGroupProjectsResponses,
    ListGroupProjectsErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/groups/{group_id}/projects',
    ...options,
  })

/**
 * Attach a project to group
 */
export const attachGroupToProject = <ThrowOnError extends boolean = false>(
  options: Options<AttachGroupToProjectData, ThrowOnError>
): RequestResult<
  AttachGroupToProjectResponses,
  AttachGroupToProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AttachGroupToProjectResponses,
    AttachGroupToProjectErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/groups/{group_id}/projects',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Update project perms for group
 */
export const permitGroupProject = <ThrowOnError extends boolean = false>(
  options: Options<PermitGroupProjectData, ThrowOnError>
): RequestResult<
  PermitGroupProjectResponses,
  PermitGroupProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PermitGroupProjectResponses,
    PermitGroupProjectErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/groups/{group_id}/projects',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Fetch all available users
 */
export const listUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersData, ThrowOnError>
): RequestResult<ListUsersResponses, ListUsersErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListUsersResponses,
    ListUsersErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/users',
    ...options,
  })

/**
 * Create a new user
 */
export const createUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserData, ThrowOnError>
): RequestResult<CreateUserResponses, CreateUserErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateUserResponses,
    CreateUserErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete a specific user
 */
export const deleteUser = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUserData, ThrowOnError>
): RequestResult<DeleteUserResponses, DeleteUserErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteUserResponses,
    DeleteUserErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/users/{user_id}',
    ...options,
  })

/**
 * Fetch a specific user
 */
export const showUser = <ThrowOnError extends boolean = false>(
  options: Options<ShowUserData, ThrowOnError>
): RequestResult<ShowUserResponses, ShowUserErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ShowUserResponses,
    ShowUserErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/users/{user_id}',
    ...options,
  })

/**
 * Update a specific user
 */
export const updateUser = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserData, ThrowOnError>
): RequestResult<UpdateUserResponses, UpdateUserErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateUserResponses,
    UpdateUserErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/users/{user_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Unlink a group from user
 */
export const deleteUserFromGroup = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUserFromGroupData, ThrowOnError>
): RequestResult<
  DeleteUserFromGroupResponses,
  DeleteUserFromGroupErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteUserFromGroupResponses,
    DeleteUserFromGroupErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/users/{user_id}/groups',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Fetch all groups attached to user
 */
export const listUserGroups = <ThrowOnError extends boolean = false>(
  options: Options<ListUserGroupsData, ThrowOnError>
): RequestResult<ListUserGroupsResponses, ListUserGroupsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ListUserGroupsResponses,
    ListUserGroupsErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/users/{user_id}/groups',
    ...options,
  })

/**
 * Attach a group to user
 */
export const attachUserToGroup = <ThrowOnError extends boolean = false>(
  options: Options<AttachUserToGroupData, ThrowOnError>
): RequestResult<
  AttachUserToGroupResponses,
  AttachUserToGroupErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AttachUserToGroupResponses,
    AttachUserToGroupErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/users/{user_id}/groups',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Update group perms for user
 */
export const permitUserGroup = <ThrowOnError extends boolean = false>(
  options: Options<PermitUserGroupData, ThrowOnError>
): RequestResult<
  PermitUserGroupResponses,
  PermitUserGroupErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PermitUserGroupResponses,
    PermitUserGroupErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/users/{user_id}/groups',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Unlink a project from user
 */
export const deleteUserFromProject = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUserFromProjectData, ThrowOnError>
): RequestResult<
  DeleteUserFromProjectResponses,
  DeleteUserFromProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteUserFromProjectResponses,
    DeleteUserFromProjectErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/users/{user_id}/projects',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Fetch all projects attached to user
 */
export const listUserProjects = <ThrowOnError extends boolean = false>(
  options: Options<ListUserProjectsData, ThrowOnError>
): RequestResult<
  ListUserProjectsResponses,
  ListUserProjectsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListUserProjectsResponses,
    ListUserProjectsErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/users/{user_id}/projects',
    ...options,
  })

/**
 * Attach a project to user
 */
export const attachUserToProject = <ThrowOnError extends boolean = false>(
  options: Options<AttachUserToProjectData, ThrowOnError>
): RequestResult<
  AttachUserToProjectResponses,
  AttachUserToProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AttachUserToProjectResponses,
    AttachUserToProjectErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/users/{user_id}/projects',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Update project perms for user
 */
export const permitUserProject = <ThrowOnError extends boolean = false>(
  options: Options<PermitUserProjectData, ThrowOnError>
): RequestResult<
  PermitUserProjectResponses,
  PermitUserProjectErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PermitUserProjectResponses,
    PermitUserProjectErrors,
    ThrowOnError
  >({
    security: [
      { name: 'X-API-Key', type: 'apiKey' },
      { scheme: 'bearer', type: 'http' },
      { scheme: 'basic', type: 'http' },
    ],
    url: '/users/{user_id}/projects',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
